### ISSUE TITLE
Header covers nav in update.jade template somehow

### ISSUE THREAD

**Issue by dannyshaw** [dannyshaw/our-school-liberia#1]
There is an invisible <header> element covering the navigation bar when viewing an individual update. Assumed to be located in update.jade

![screenshot from 2016-04-11 12 49 08](https://cloud.githubusercontent.com/assets/603175/14415664/e9efeb64-ffe4-11e5-83e6-b3116e1b5b87.png)

**Comment by iamandrea** [comment]
Hey @dannyshaw - I vaguely remember you solving this one, or is this still an issue?
