### ISSUE TITLE
Contact us form submission

### ISSUE THREAD

**Issue by iamandrea** [dannyshaw/our-school-liberia#10]
When the contact form is submitted, there's an error:

> Sorry, an error occurred loading the page (500)
> 
> C:\Users\Andrea\Documents\GitHub\our-school-liberia\templates\views\contact.pug:13
> 11| form(method='post') 
> 12| input(type='hidden', name='action', value='contact') 
> > 13| .form-group(class=validationErrors.name ? 'has-error' : null) 
> 14| label Name 
> 15| input(type='text', name='name', value=formData['name']).form-control 
> 16| .form-group(class=validationErrors.email ? 'has-error' : null) 
> 
> Cannot read property 'name' of undefined

I may need your help on this one as I can't work out why name isn't defined.

**Comment by dannyshaw** [comment]
I couldn't reproduce this error. submission worked for me?
