### ISSUE TITLE
Contact us: Remove bank details from bottom of page

### ISSUE THREAD

**Issue by ourschoolliberia** [dannyshaw/our-school-liberia#26]
These details shouldn't be here, but would like bank details on the 'donate' page to the left of the paypal option.

Is it possible to hide the paypal code for now, but leave it there so we could easily set it up at a later date? Some issues from my end setting this up for the school, but do intend to do it in future.

**Comment by ourschoolliberia** [comment]
Bank account details are below.

Intermediary bank: Ghana International Bank Ltd
Intermediary bank address: London
Intermediary SWIFT code: GHIBGB2L

Beneficiary bank: International Bank (Liberia) Ltd 
Beneficiary bank address: 64 Broad Street, Monrovia, Liberia
Beneficiary bank SWIFT code: IBLRLRLM

Beneficiary name: Liberia Renaissance Education Complex
Beneficiary account number: 10.2010-101977-01
IBAN No: GB62 GHIB 7006 1310170907

**Comment by dannyshaw** [comment]
Resolved in https://github.com/dannyshaw/our-school-liberia/pull/32
