### ISSUE TITLE
Updates page: text spacing and gallery links

### ISSUE THREAD

**Issue by ourschoolliberia** [dannyshaw/our-school-liberia#27]
'postedon' and '2017by' need spaces.

Back-end has option to upload/link a gallery, but gallery/link aren't appearing on finished page.

**Comment by dannyshaw** [comment]
@ourschoolliberia do you want Galleries to be a browseable menuitem/interface seperate to galleries that are attached to posts?

**Comment by ourschoolliberia** [comment]
Not sure if you still need a response on this, but no need for separate menu interface.
