### ISSUE TITLE
Annual reports

### ISSUE THREAD

**Issue by ourschoolliberia** [dannyshaw/our-school-liberia#28]
Remove annual reports page, or at least hide page and link for now in such a way that it could be re-activated later.

**Comment by dannyshaw** [comment]
resolved in https://github.com/dannyshaw/our-school-liberia/pull/32

@AndreasMeyer1 great work again hooking up this page with S3. Unfortunately it was actually requested we remove this a while back. Sorry, the work done will no doubt be very useful for other uploads around the site but this particular section will be disabled.

Much appreciated.
