### ISSUE TITLE
Submitting Volunteer and Subscribe forms

### ISSUE THREAD

**Issue by iamandrea** [dannyshaw/our-school-liberia#6]

**Comment by dannyshaw** [comment]
- [x] Volunteer Submission
- [ ] Subscriptions

**Comment by dannyshaw** [comment]
Check out these files:

- `routes/views/volunteer.js`
- `models/VolunteerSubmission.js`
- `templates/views/get-involved-volunteer.jade`
- and the [route map](https://github.com/dannyshaw/our-school-liberia/blob/master/routes/languageRouteMap.js#L194-L206)

They all work together to create a submission. note the `method: all` in the route map. This means the controller handles when there is a POST as well as a GET.

**Comment by dannyshaw** [comment]
Both forms submitting and emailing, subscribe needs email to be tweaked.
Gonna make volunteer submission have a checkbox (opt out) to automatically enter a subscribe entry as well.

**Comment by iamandrea** [comment]
Thanks for this @dannyshaw - do you know how the error message is being pulled in by any chance?

I want to try and separate it from the .content-container class so that I can change the position of it.

**Comment by dannyshaw** [comment]
The `templates/mixins/flash-messages.pug` brings it in, it is called in the `default.pug` template. looks to be ouside .content-container already? not sure

**Comment by dannyshaw** [comment]
@ourschoolliberia are these forms required to be both in english and german?
