### ISSUE TITLE
Hero Image covers entire page on an average sized screen

### ISSUE THREAD

**Issue by dannyshaw** [dannyshaw/our-school-liberia#8]
It's been requested to make it perhaps narrower somehow.. The girls look great in the big banner, but as it stands, because it takes most of the screen, clicking different links do not actually chnge anything on the visible portion of page.

Perhaps the home page could have a large banner with some kind of smaller version for other pages with titles visible above-the-fold?

**Comment by iamandrea** [comment]
Media queries have been revised so that the height always peeks through on smaller viewports (other than mobile)
